require("plugins.packer")
require("plugins.nvim-tree")
require("plugins.colorscheme")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.toggleterm")
require("plugins.nvim-autopairs")
